In [ ]:
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(os.getcwd())))
from poker.agents.game_state import GameState, Player
from poker.agents.game_state import *
from poker.core.card import *
from poker.core.card import Rank
from agents.deep_learning_agent import PokerPlayerNetV1


import os
import sys
from typing import List, Dict, Tuple, Optional, Any
from poker.agents.game_state import GameStateBuilder
from poker.agents.game_state import GameStateRetriever
from poker.core.gamestage import Stage
from poker.core.action import Action

import random
import numpy as np
import torch
import itertools

In [2]:
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

In [3]:
set_seed(42)

In [4]:
my_agent = PokerPlayerNetV1(use_batchnorm=False)

## Loading

In [5]:
my_agent.load_state_dict(torch.load("a9e8c8.14060308.st"))

<All keys matched successfully>

In [6]:
my_agent.aggressiveness_call = 1.0 # CUSTOM AGRESSIVENESS, default is 1.0
my_agent.aggressiveness_raise = 1.5

## Testing

In [ ]:
from poker.agents.game_state import GameState, Player
from poker.agents.game_state import *
from poker.core.card import *
from poker.core.card import Rank

In [8]:
p1 = Player(1, (Card(Rank.ACE, Suit.SPADE), Card(Rank.ACE, Suit.CLUB)), 100)
p2 = Player(0, None, 80)
p3 = Player(2, None, 90)

In [9]:
game_state = GameState(
    stage = Stage.PREFLOP,
    community_cards = [],
    pot_size = 3,
    min_bet_to_continue = 0,
    my_player = p1,
    other_players = [p2, p3],
    my_player_action = (Action.RAISE, 10),
)

In [10]:
my_agent.eval_game_state(game_state)

(tensor([0.0366, 0.0245, 0.9389]), tensor(1.5549))

In [11]:
p1 = Player(1, (Card(Rank.TWO, Suit.SPADE), Card(Rank.SEVEN, Suit.CLUB)), 100)
p2 = Player(0, None, 80)
p3 = Player(2, None, 90)

In [12]:
game_state = GameState(
    stage = Stage.PREFLOP,
    community_cards = [],
    pot_size = 3,
    min_bet_to_continue = 0,
    my_player = p1,
    other_players = [p2, p3],
    my_player_action = (Action.RAISE, 10),
)

In [13]:
my_agent.eval_game_state(game_state)

(tensor([0.9202, 0.0159, 0.0639]), tensor(1.5455))

In [14]:
p1 = Player(1, (Card(Rank.ACE, Suit.SPADE), Card(Rank.KING, Suit.CLUB)), 100)
p2 = Player(0, None, 80)
p3 = Player(2, None, 90)

In [15]:
game_state = GameState(
    stage = Stage.PREFLOP,
    community_cards = [],
    pot_size = 3,
    min_bet_to_continue = 0,
    my_player = p1,
    other_players = [p2, p3],
    my_player_action = (Action.RAISE, 10),
)

In [16]:
my_agent.eval_game_state(game_state)

(tensor([0.4754, 0.0380, 0.4866]), tensor(1.5360))